### PR TITLE
feat(sponsorcommunity): add clearsky networks

### PR DESCRIPTION
**Pull request by jvandemo**
This PR adds Clearsky Networks to Community Partners

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Do we have a sharper logo for them? Might look sharp when downsized though.

**Review by samvloeberghs — APPROVED** [review]

**Comment by samvloeberghs** [comment]
logo can be updated later if needed :)

**Comment by jvandemo** [comment]
Thanks @samvloeberghs 👍

**Comment by SamVerschueren** [comment]
Logo looks fine on the website! :tada:

**Pull request merged**
